### ISSUE TITLE
new dataset

### ISSUE THREAD

**Issue by dnnguifever** [ymym3412/DeepEmbeddedClustering#1]
Hello, thank you for your post. 

I am wondering, how can I use the code on my own dataset, a folder of images? 

Thanks!

**Comment by ymym3412** [comment]
Deep Embedded Clustering model expect input data as 1-dim vector.  
In my code, one MNIST image is represented as 1-dim numpy vector which shape is (784,).  

```py
>>> from chainer.datasets import mnist
>>> train, _ = mnist.get_mnist()
>>> train[0][0].shape
(784,)
```

So you should linearize your images for Deep Embedded Clustering model like this.  

```py
>>> import cv2
>>> im = cv2.imread('sampe.png')
>>> im.shape
(240, 240, 3)
>>>
>>> linearized = im.reshape(-1)
>>> linearized.shape
(172800,)
```

But dimension of linearized image is very big.  
In the paper, authors used HOG feature and a 8-by-8 color map as input for STL-10 dataset and final feature size is 1428.  
>We also used the unlabeled set when training our autoencoders. Similar to Doersch et al. (2012), we concatenated HOG feature and a 8-by-8 color map to use as input to all algorithms.

Thanks.

**Comment by dnnguifever** [comment]
Thanks!
